---

name: ebrick-fpga-cad CI Test
on:
  # Runs on all PRs
  push:
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

env:
  REPO_PATH: "/__w/ebrick-fpga-cad/ebrick-fpga-cad"

jobs:
  ci_test:
    name: Run ebrick-fpga CAD flow tests

    runs-on: ubuntu-latest

    env:
      GIT_TOKEN: ${{ secrets.ZA_TOKEN }}
      PYTHONPATH: ${{ env.REPO_PATH }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_PATH }}

      - name: Install Requirements
        run: |
          python3 -m venv clean_env
          source clean_env/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          source clean_env/bin/activate
          pytest tests
