---

name: Regression
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run CAD flow tests

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/siliconcompiler/sc_runner:latest

    env:
      GIT_TOKEN: ${{ secrets.ZA_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup git access
        run: |
          git config --global --add url."https://github.com/".insteadOf git@github.com:

      - name: Setup python
        run: |
          python3 -m venv --system-site-packages .efpga
          . .efpga/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -e .[test]
          pip3 install -r examples/requirements.txt

      - name: Run tests
        run: |
          . .efpga/bin/activate
          pytest
